name: Update Sitemap

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # ここで明示的に標準のトークンを使い切る設定にします
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_sitemap.py

      - name: Commit and Push changes
        run: |
          # ユーザー情報をActions公式のものに固定
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add sitemap.xml
          
          # 差分があるときだけ処理
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "Update sitemap.xml [skip ci]"
            # ブランチ名を自動取得してプッシュ
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
